local pomodoro = require("pomodoro")

describe("format_time", function()
  it("formats zero as 00:00", function()
    assert.equals("00:00", pomodoro._format_time(0))
  end)

  it("formats 90 seconds as 01:30", function()
    assert.equals("01:30", pomodoro._format_time(90))
  end)

  it("formats 25 minutes (1500 seconds) as 25:00", function()
    assert.equals("25:00", pomodoro._format_time(1500))
  end)

  it("formats 5 minutes (300 seconds) as 05:00", function()
    assert.equals("05:00", pomodoro._format_time(300))
  end)
end)

describe("statusline", function()
  before_each(function()
    -- Ensure stopped state before each test
    pomodoro._reset_state()
  end)

  it("returns empty string when not running", function()
    assert.equals("", pomodoro.statusline())
  end)

  it("returns work icon and time when in work phase", function()
    pomodoro._set_state({ running = true, phase = "work", remaining_seconds = 1500 })
    assert.equals("🍅 25:00", pomodoro.statusline())
  end)

  it("returns break icon and time when in break phase", function()
    pomodoro._set_state({ running = true, phase = "break", remaining_seconds = 300 })
    assert.equals("☕ 05:00", pomodoro.statusline())
  end)

  it("returns empty string after stop", function()
    pomodoro._set_state({ running = true, phase = "work", remaining_seconds = 100 })
    pomodoro._reset_state()
    assert.equals("", pomodoro.statusline())
  end)
end)

describe("load_config", function()
  before_each(function()
    pomodoro._reset_state()
    pomodoro._load_config("/nonexistent/path/reset")
  end)

  it("uses defaults when config file does not exist", function()
    pomodoro._load_config("/nonexistent/path/pomodoro.lua")
    assert.equals(25, pomodoro._get_config().work_minutes)
    assert.equals(5, pomodoro._get_config().break_minutes)
  end)

  it("loads work_minutes from config file", function()
    local tmp = vim.fn.tempname() .. ".lua"
    local f = io.open(tmp, "w")
    f:write("return { work_minutes = 50, break_minutes = 10 }")
    f:close()
    pomodoro._load_config(tmp)
    assert.equals(50, pomodoro._get_config().work_minutes)
    assert.equals(10, pomodoro._get_config().break_minutes)
    os.remove(tmp)
  end)

  it("falls back to defaults for missing keys in config file", function()
    local tmp = vim.fn.tempname() .. ".lua"
    local f = io.open(tmp, "w")
    f:write("return { work_minutes = 45 }")
    f:close()
    pomodoro._load_config(tmp)
    assert.equals(45, pomodoro._get_config().work_minutes)
    assert.equals(5, pomodoro._get_config().break_minutes)
    os.remove(tmp)
  end)

  it("falls back to defaults when config file has a syntax error", function()
    local tmp = vim.fn.tempname() .. ".lua"
    local f = io.open(tmp, "w")
    f:write("return {{{")
    f:close()
    pomodoro._load_config(tmp)
    assert.equals(25, pomodoro._get_config().work_minutes)
    assert.equals(5, pomodoro._get_config().break_minutes)
    os.remove(tmp)
  end)

  it("has default long_break_minutes of 15", function()
    pomodoro._load_config("/nonexistent/path/reset")
    assert.equals(15, pomodoro._get_config().long_break_minutes)
  end)

  it("has default long_break_interval of 4", function()
    pomodoro._load_config("/nonexistent/path/reset")
    assert.equals(4, pomodoro._get_config().long_break_interval)
  end)
end)

describe("timer state transitions", function()
  before_each(function()
    pomodoro._reset_state()
    pomodoro._set_state({ config = { work_minutes = 25, break_minutes = 5, long_break_minutes = 15, long_break_interval = 4 } })
  end)

  describe("start()", function()
    it("sets running to true", function()
      pomodoro._start_phase("work")
      assert.is_true(pomodoro._get_state().running)
    end)

    it("sets remaining_seconds to work_minutes * 60", function()
      pomodoro._start_phase("work")
      assert.equals(25 * 60, pomodoro._get_state().remaining_seconds)
    end)

    it("sets phase to work for work phase", function()
      pomodoro._start_phase("work")
      assert.equals("work", pomodoro._get_state().phase)
    end)

    it("sets remaining_seconds to break_minutes * 60 for break phase", function()
      pomodoro._start_phase("break")
      assert.equals(5 * 60, pomodoro._get_state().remaining_seconds)
    end)

    it("sets remaining_seconds to long_break_minutes * 60 for long_break phase", function()
      pomodoro._start_phase("long_break")
      assert.equals(15 * 60, pomodoro._get_state().remaining_seconds)
    end)
  end)

  describe("stop()", function()
    it("sets running to false", function()
      pomodoro._start_phase("work")
      pomodoro.stop()
      assert.is_false(pomodoro._get_state().running)
    end)

    it("resets remaining_seconds to 0", function()
      pomodoro._start_phase("work")
      pomodoro.stop()
      assert.equals(0, pomodoro._get_state().remaining_seconds)
    end)

    it("resets phase to idle", function()
      pomodoro._set_state({ running = true, phase = "break", remaining_seconds = 100 })
      pomodoro.stop()
      assert.equals("idle", pomodoro._get_state().phase)
    end)
  end)

  describe("tick()", function()
    it("decrements remaining_seconds by 1", function()
      pomodoro._set_state({ running = true, phase = "work", remaining_seconds = 100 })
      pomodoro._tick(0)  -- gen=0 since _reset_state resets _generation to 0
      assert.equals(99, pomodoro._get_state().remaining_seconds)
    end)

    it("does not go below 0", function()
      pomodoro._set_state({ running = true, phase = "work", remaining_seconds = 0 })
      pomodoro._tick(0)  -- gen=0 since _reset_state resets _generation to 0
      assert.is_true(pomodoro._get_state().remaining_seconds >= 0)
    end)

    it("when remaining_seconds is 0 and in work phase, starts a break", function()
      pomodoro._set_state({ running = true, phase = "work", remaining_seconds = 0 })
      pomodoro._tick(0)  -- gen=0 since _reset_state resets _generation to 0
      local s = pomodoro._get_state()
      assert.equals("break", s.phase)
      assert.is_true(s.running)
      assert.equals(5 * 60, s.remaining_seconds)
    end)

    it("when remaining_seconds is 0 and in break phase, stops the timer", function()
      pomodoro._set_state({ running = true, phase = "break", remaining_seconds = 0 })
      pomodoro._tick(0)  -- gen=0 since _reset_state resets _generation to 0
      local s = pomodoro._get_state()
      assert.is_false(s.running)
      assert.equals("idle", s.phase)
    end)
  end)

  describe("skip()", function()
    it("during work phase starts break", function()
      pomodoro._set_state({ running = true, phase = "work", remaining_seconds = 500 })
      pomodoro.skip()
      assert.equals("break", pomodoro._get_state().phase)
      assert.is_true(pomodoro._get_state().running)
    end)

    it("during break phase stops timer", function()
      pomodoro._set_state({ running = true, phase = "break", remaining_seconds = 100 })
      pomodoro.skip()
      assert.is_false(pomodoro._get_state().running)
    end)

    it("does nothing when not running", function()
      pomodoro._reset_state()
      pomodoro.skip()
      assert.is_false(pomodoro._get_state().running)
      assert.equals("idle", pomodoro._get_state().phase)
      assert.equals(0, pomodoro._get_state().remaining_seconds)
    end)
  end)

  describe("toggle()", function()
    it("stops when running", function()
      pomodoro._set_state({ running = true, phase = "work", remaining_seconds = 500 })
      pomodoro.toggle()
      assert.is_false(pomodoro._get_state().running)
    end)

    it("starts when not running", function()
      pomodoro._reset_state()
      pomodoro.toggle()
      assert.is_true(pomodoro._get_state().running)
    end)
  end)
end)

describe("setup()", function()
  before_each(function()
    pomodoro._reset_state()
  end)

  it("registers PomodoroStart command", function()
    pomodoro.setup()
    local cmds = vim.api.nvim_get_commands({})
    assert.is_not_nil(cmds["PomodoroStart"])
  end)

  it("registers PomodoroStop command", function()
    pomodoro.setup()
    local cmds = vim.api.nvim_get_commands({})
    assert.is_not_nil(cmds["PomodoroStop"])
  end)

  it("registers PomodoroSkip command", function()
    pomodoro.setup()
    local cmds = vim.api.nvim_get_commands({})
    assert.is_not_nil(cmds["PomodoroSkip"])
  end)

  it("registers PomodoroToggle command", function()
    pomodoro.setup()
    local cmds = vim.api.nvim_get_commands({})
    assert.is_not_nil(cmds["PomodoroToggle"])
  end)

  it("accepts inline opts to override config", function()
    pomodoro.setup({ work_minutes = 45, break_minutes = 10 })
    assert.equals(45, pomodoro._get_config().work_minutes)
    assert.equals(10, pomodoro._get_config().break_minutes)
  end)

  it("can be called twice without error", function()
    pomodoro.setup()
    assert.has_no.errors(function() pomodoro.setup() end)
  end)
end)
